/* Generated By:JavaCC: Do not edit this line. musiclangConstants.java */
package musicLang;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface musiclangConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int L = 5;
  /** RegularExpression Id. */
  int R = 6;
  /** RegularExpression Id. */
  int C = 7;
  /** RegularExpression Id. */
  int PitchToken = 8;
  /** RegularExpression Id. */
  int DurationToken = 9;
  /** RegularExpression Id. */
  int TrackToken = 10;
  /** RegularExpression Id. */
  int PlayToken = 11;
  /** RegularExpression Id. */
  int InstrumentIdToken = 12;
  /** RegularExpression Id. */
  int InstrumentNumToken = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "<PitchToken>",
    "<DurationToken>",
    "\"@\"",
    "\">\"",
    "\"i\"",
    "<InstrumentNumToken>",
  };

}
